### ISSUE TITLE
Custom node path not work on my computer (windows)

### ISSUE THREAD

**Issue by draco1023** [victorporof/Sublime-HTMLPrettify#257]
Error message :
```
Using node.js path on 'windows': G:/Portable/SublimeText3/3rd/nodejs/node.exe
b''
Unexpected error(<class 'Exception'>): Command G:/Portable/SublimeText3/3rd/nodejs/node.exe" "G:\Portable\SublimeText3\Data\Packages\HTML-CSS-JS Prettify/scripts/run.js" "G:\Portable\SublimeText3\Data\Packages\HTML-CSS-JS Prettify/.__temp__" "H:\Workspace\pages\lx\index.html created invalid output.
error: You won't be able to use this plugin without specifying the path to node.js.
Traceback (most recent call last):
  File "G:\Portable\SublimeText3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "G:\Portable\SublimeText3\Data\Packages\HTML-CSS-JS Prettify\HTMLPrettify.py", line 48, in run
    print(self.get_output_diagnostics(output))
  File "G:\Portable\SublimeText3\Data\Packages\HTML-CSS-JS Prettify\HTMLPrettify.py", line 110, in get_output_diagnostics
    index = output.find(OUTPUT_VALID)
AttributeError: 'NoneType' object has no attribute 'find'
```
node version 0.12.0 x64 (portable)
sublime text build 3083 x64 (portable)
windows 10 x64

**Comment by bixibu** [comment]
+1

Using node.js path on 'windows': D:/Utilisateurs/xxx/_Softs/nodejs/node.exe
Unexpected error(<class 'OSError'>): [WinError 6] Descripteur non valide
error: You won't be able to use this plugin without specifying the path to node.js.
Traceback (most recent call last):
  File "D:\Utilisateurs\xxx\_Softs\Sublime Text Build 3083 x64\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "D:\Utilisateurs\xxx\_Softs\Sublime Text Build 3083 x64\Data\Packages\HTML-CSS-JS Prettify\HTMLPrettify.py", line 48, in run
    print(self.get_output_diagnostics(output))
  File "D:\Utilisateurs\xxx\_Softs\Sublime Text Build 3083 x64\Data\Packages\HTML-CSS-JS Prettify\HTMLPrettify.py", line 110, in get_output_diagnostics
    index = output.find(OUTPUT_VALID)
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by draco1023** [comment]
Reinstall then it works

**Comment by spawnrider** [comment]
Reinstall it does not work for me. 
Same error ....
