### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by rwalsh0975** [victorporof/Sublime-HTMLPrettify#473]
`Node.js encountered a runtime error: /Users/xxx/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/Users/xxxx/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1144:25)
    at Function.Module._resolveLookupPaths (module.js:376:17)
    at Function.Module._resolveFilename (module.js:446:31)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxxx/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:138:18)
    at Module._compile (module.js:556:32)`

**Comment by rwalsh0975** [comment]
I found this happens if you have multiple sublime windows open.
