### ISSUE TITLE
Crashing when trying to format Big JSON file . Without any warning -

### ISSUE THREAD

**Issue by sap9433** [victorporof/Sublime-HTMLPrettify#498]
Crashing when trying to format Big JSON file . Without any warning -

Error log - (Node v6.2.2 , MacOs Sierra)
Node.js encountered a runtime error: /Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:138:18)
    at Module._compile (module.js:570:32)

Node.js encountered a runtime error: /Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:138:18)
    at Module._compile (module.js:570:32)

Node.js encountered a runtime error: /Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sachatterjee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:138:18)
    at Module._compile (module.js:570:32)

**Comment by victorporof** [comment]
Duping to https://github.com/victorporof/Sublime-HTMLPrettify/issues/487
More investigation needed. Can you post an example file?
