### ISSUE TITLE
Unable to prettify

### ISSUE THREAD

**Issue by anudeepjusanu** [victorporof/Sublime-HTMLPrettify#522]
Unable to prettify getting runtime error

**Comment by sathisz** [comment]
@anudeepjusanu Could you share the screenshot

**Comment by kondanta** [comment]
I'm having the same issue, and this is what i got after trying to prettify.

```js
Node.js encountered a runtime error: /home/kondanta/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/home/kondanta/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1175:25)
    at Function.Module._resolveLookupPaths (module.js:431:17)
    at Function.Module._resolveFilename (module.js:549:20)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kondanta/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:138:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

**Comment by kaushal9678** [comment]
Just close your current terminal window and run again ios, android commands. It will work.
