### ISSUE TITLE
Node.js encountered a runtime error: module.js:540

### ISSUE THREAD

**Issue by hoemon** [victorporof/Sublime-HTMLPrettify#613]
```
Node.js encountered a runtime error: module.js:540

    throw err;

    ^



Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (module.js:538:15)

    at Function.Module._load (module.js:468:25)

    at Module.require (module.js:587:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\...\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:14:1)

    at Module._compile (module.js:643:30)

    at Object.Module._extensions..js (module.js:654:10)

    at Module.load (module.js:556:32)

    at tryModuleLoad (module.js:499:12)

    at Function.Module._load (module.js:491:3)

```

When I try to prettify JS code, this happens.

Node 10.11.0

**Comment by shlllshlll** [comment]
A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

**Comment by diegocanal** [comment]
Thanks @shlllshlll your solution worked for me!

**Comment by UXJester** [comment]
> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

Thanks this worked.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
