### ISSUE TITLE
Node.js encountered a runtime error: module.js:550

### ISSUE THREAD

**Issue by sam80719** [victorporof/Sublime-HTMLPrettify#614]
Hi Dears:

i could not use HTMLPrettify, i added directly node path with osx env
my path is : /Users/chenmingsan/.nvm/versions/node/v8.12.0/bin/node

but it showed error:( 
any advise, please

error log:
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Node.js encountered a runtime error: module.js:550
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chenmingsan/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/utils/configUtils.js:14:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by hoemon** [comment]
we're having similar errors, so maybe an update broke something..

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll in [Issue \#613](https://github.com/victorporof/Sublime-HTMLPrettify/issues/613)?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
