### ISSUE TITLE
Cannot find module 'core-js/modules/es7.object.entries'

### ISSUE THREAD

**Issue by Hungdq** [victorporof/Sublime-HTMLPrettify#620]
Hi Victorporof,

I have encountered this error whenever I try to use prettify command (Ctrl + Shift + H). I have been trying to install core-js package but it didn't help. Please help me figure out what's wrong? 

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hung/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/utils/configUtils.js:14:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Jentagawa** [comment]
have you tried
`npm i core-js -g`

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll in [Issue \#613](https://github.com/victorporof/Sublime-HTMLPrettify/issues/613)?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It specifies it has to be run in the packages folder. It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
