### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by Bogdan808** [victorporof/Sublime-HTMLPrettify#623]
Node.js encountered a runtime error: module.js:557

    throw err;

    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (module.js:555:15)

    at Function.Module._load (module.js:482:25)

    at Module.require (module.js:604:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\Users\Bogdan\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:14:1)

    at Module._compile (module.js:660:30)

    at Object.Module._extensions..js (module.js:671:10)

    at Module.load (module.js:573:32)

    at tryModuleLoad (module.js:513:12)

    at Function.Module._load (module.js:505:3)

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll in [Issue \#613](https://github.com/victorporof/Sublime-HTMLPrettify/issues/613)?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
