### ISSUE TITLE
a runtime error was encountered in the prettifier

### ISSUE THREAD

**Issue by Bundbary** [victorporof/Sublime-HTMLPrettify#628]
I updated node.js a couple of days ago as instructed by Sublime. Suddenly today, after working fine all morning, it started throwing this error. I've tried a reboot.

Node.js encountered a runtime error: module.js:550

    throw err;

    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (module.js:548:15)

    at Function.Module._load (module.js:475:25)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\Users\bpenn\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:14:1)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)

**Comment by Bundbary** [comment]
I was just trying diegocanal's fix when victorporofs comment came thru, so I'm not sure which one was responsible for fixing it, but it's working fine again. Thank you both!

**Comment by victorporof** [comment]
Awesome, thanks!
