### ISSUE TITLE
Runtime error when attempting to run prettify on MacOS 10.13.6

### ISSUE THREAD

**Issue by aokeefe17** [victorporof/Sublime-HTMLPrettify#631]
Receiving a runtime error message when I attempt to use Prettify. The message started appearing after I updated the node.js (which was requested by application due to it being too old). I attempted to download a new version of Sublime, old and new versions of node.js, 8.12.0 and 10.11.0.  Unsure of how to resolve.

Error message:
**A runtime error was encountered in the prettifier. See the console output for more information.** 

Console log:

Node.js encountered a runtime error: module.js:550
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/okeefa2/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/utils/configUtils.js:14:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by paulalbertheliopsis** [comment]
Same bug here !

**Comment by finscn** [comment]
Same bug here

**Comment by UXJester** [comment]
Solution for @shlllshlll
> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

This resolved my issue.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
