### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by fishmi** [victorporof/Sublime-HTMLPrettify#632]
I get folowing error in the console:

Node.js encountered a runtime error: module.js:549

    throw err;

    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (module.js:547:15)

    at Function.Module._load (module.js:474:25)

    at Module.require (module.js:596:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\Users\Martin Ische\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:14:1)

    at Module._compile (module.js:652:30)

    at Object.Module._extensions..js (module.js:663:10)

    at Module.load (module.js:565:32)

    at tryModuleLoad (module.js:505:12)

    at Function.Module._load (module.js:497:3)

**Comment by fishmi** [comment]
Temporary solution with npm install core-js solve the problem

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
